---

apache::apache_name: 'httpd24'
apache::apache_version: '2.4'
apache::package_ensure: '2.4.25-1.68.amzn1' 
aem_quickstart_source: 's3://mb-aem-artifacts/adobeaemcloud/AEM_6.2_Quickstart.jar'
aem_license_source: 's3://mb-aem-artifacts/adobeaemcloud/license-6.2.properties'

dispatcher::aem_dispatcher_source: 'https://www.adobeaemcloud.com/content/companies/public/adobe/dispatcher/dispatcher/_jcr_content/top/download_8/file.res/dispatcher-apache2.4-linux-x86-64-4.2.2.tar.gz'
dispatcher::filename: 'dispatcher-apache2.4-linux-x86-64-4.2.2.tar.gz'
dispatcher::module_filename: 'dispatcher-apache2.4-4.2.2.so'


